### ISSUE TITLE
Deprecated documentation

### ISSUE THREAD

**Issue by iformas** [TransbankDevelopers/transbank-sdk-dotnet#44]
https://www.transbankdevelopers.cl/referencia/webpay?csharp#webpay-plus-normal
https://www.transbankdevelopers.cl/documentacion/webpay?csharp#crear-una-transaccion

There is no "Webpay" class.
There is no "Configuration" class.
There is no"Configuration.ForTestingWebpayPlusNormal"

```
var transaction =
    new Webpay(Configuration.ForTestingWebpayPlusNormal).NormalTransaction;
```

**Comment by afiebig** [comment]
Docs in TransbankDevelopers.cl stated that you needed to use libwebpay for C#, this is no longer needed since version [2.0.0](https://github.com/TransbankDevelopers/transbank-sdk-dotnet/releases/tag/v2.0.0)

Webpay support was added here https://github.com/TransbankDevelopers/transbank-sdk-dotnet/pull/45
